// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD06CRvB_riL7EGnIgP3I-5KSTrL1iEqWU',
    appId: '1:919849413761:web:aff7afd1bdc77733103180',
    messagingSenderId: '919849413761',
    projectId: 'hagar1',
    authDomain: 'hagar1.firebaseapp.com',
    storageBucket: 'hagar1.appspot.com',
    measurementId: 'G-1FV8V1PP2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLmuKDaxofG4MybkuzD-HNOBBRE0Z3Vqc',
    appId: '1:919849413761:android:2d9efc452b1b693f103180',
    messagingSenderId: '919849413761',
    projectId: 'hagar1',
    storageBucket: 'hagar1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfrIxOcTzB-Dbsb2QJVcTrSiSsTO8rDJI',
    appId: '1:919849413761:ios:c38230ef28f3d57e103180',
    messagingSenderId: '919849413761',
    projectId: 'hagar1',
    storageBucket: 'hagar1.appspot.com',
    androidClientId: '919849413761-6s0q3c160kf4hlk1qcljva8u5b1o88a5.apps.googleusercontent.com',
    iosClientId: '919849413761-03n20oe1jr6rk9vtre6992ppih6r2p23.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfrIxOcTzB-Dbsb2QJVcTrSiSsTO8rDJI',
    appId: '1:919849413761:ios:6f494be3d9cd09d2103180',
    messagingSenderId: '919849413761',
    projectId: 'hagar1',
    storageBucket: 'hagar1.appspot.com',
    androidClientId: '919849413761-6s0q3c160kf4hlk1qcljva8u5b1o88a5.apps.googleusercontent.com',
    iosClientId: '919849413761-40aoe5kajbpidrd1f2jiljo1qae65bso.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
